---

vm:
  hostname: ubuntu2204
  ansible_dir: /vagrant/ansible
  data_folder: /media/sf_DATA

netplan:
  interface: enp3s0
  gateway : 10.10.10.1
  search: openstackgate.local
  dns: 10.10.10.2, 8.8.8.8, 1.1.1.1

server:
  timezone: MET
  locale: fr_FR.UTF-8
