---

- name: Copy the rq1d script
  template: src={{item.src}} dest={{item.dest}} mode='0755'
  with_items:
     - { src: 'rq1d.tpl',  dest: '/usr/local/bin/rq1d' }

- name: Copy rq1d.service file into Systemd
  copy:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/*.service
