---

- hosts: all
  become: true
  become_user: root

  vars_files:
    - vars/main.yml

  environment:
    PYTHONHTTPSVERIFY: 0

  roles:
    - server
    - snapd
    - docker
    - rq1d
    - npflow
    - nginx

  handlers:
    - name: Apply netplan
      ansible.builtin.command: netplan apply

